backend:
  name: github
  repo: ryanfiller/portfolio-gatsby

publish_mode: editorial_workflow

media_folder: static/images/uploads
public_folder: images/uploads

collections:
  - name: pages
    label: Pages
    folder: src/content/pages
    create: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }

  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: published,label: Published, widget: boolean, default: false}
      - { name: template, widget: hidden, default: blog-item}

      - { name: title, label: Title, widget: string }
      - { name: excerpt, label: excerpt, widget: text }
      - { name: banner, label: Banner, widget: image }
      - { name: path, label: Url, widget: string }
      - { name: date, label: Date, widget: date }

      - { name: category, label: Category, widget: string, required: false }
      - { name: tags, label: Tags, widget: list, required: false}

      - { name: body, label: Body, widget: markdown }

  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    fields:
      - { name: published,label: Published, widget: boolean, default: false}
      - { name: template, widget: hidden, default: portfolio-item}

      - { name: title, label: Title, widget: string }
      - { name: path, label: Url, widget: string }
      - { name: date, label: Date, widget: date }

      - { name: category, label: Category, widget: string }
      - { name: tags, label: Tags, widget: list, required: false}

      - { name: client, label: Client, widget: string, required: false }
      - { name: clienturl, label: Client Url, widget: string, required: false }
      - { name: color, label: Brand Color, widget: string }

      - { name: logocolor, label: Color Logo, widget: image, required: false }
      - { name: logowhite, label: White Logo, widget: image }

      - label: "Images"
        name: "images"
        widget: "list"
        fields:
            - {label: Image, name: image, widget: image}

      - { name: body, label: Body, widget: markdown }