backend:
  name: github
  repo: ryanfiller/portfolio-gatsby

publish_mode: editorial_workflow

media_folder: static/images

collections:
  - name: pages
    label: Pages
    folder: src/content/pages
    create: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }

  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }

  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { label: "Tags",name: "tags", widget: "list", default: ["news"]}